version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - LANG=C.UTF-8
      - TZ 'Asia/Tokyo'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: always

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    image: scraper:latest
    volumes:
      - ./app:/app
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    environment:
      - ZENN_SEARCH_KEYWORD=python
      - QIITA_SEARCH_KEYWORD=python
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
#    command: ["python", "tests/test_db.py"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s